name: 'Generate reports'

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  coverage:

    runs-on: [ubuntu-latest]
    name: Reporting on Ubuntu

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Generate coverage with JaCoCo
        run: mvn -V -ntp clean verify --file pom.xml '-Dgpg.skip'
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.0.0
        with:
          token: ${{secrets.CODECOV_TOKEN}}
      - name: Mutation Coverage
        run: mvn -V -ntp org.pitest:pitest-maven:mutationCoverage
      - name: Autograding
        uses: uhafner/autograding-github-action@v1.7.0
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HEAD_SHA: ${{github.event.pull_request.head.sha}}
          CONFIG: >
            {
              "analysis": {
                "maxScore": 100,
                "errorImpact": -5,
                "highImpact": -2,
                "normalImpact": -1,
                "lowImpact": -1
              },
              "tests": {
                "maxScore": 100,
                "failureImpact": -10
              },
              "coverage": {
                "maxScore": 100,
                "missedPercentageImpact": -1
              },
              "pit": {
                "maxScore": 100,
                "undetectedPercentageImpact": -1
              }
            }
